config/routes.rb
require 'resque/server'

Contentbird::Application.routes.draw do

  https_constraint = (Rails.env.production? ? {protocol: 'https://'} : {})
  http_catchall    = (Rails.env.production? ? {protocol: 'http://'}  : -> (params, request) {false})

  namespace :api, path: "api", constraints: https_constraint do
    scope module: :v2, constraints: ApiConstraints.new(version: 2) do
      resources :channel_info, only: [:show]
    end
    scope module: :v1, constraints: ApiConstraints.new(version: 1, default: :true) do
      resources :channel_info, only: [:show]
      get  'home/contents'                        => 'home_contents#index',     as: 'home_contents'
      get  'sections/:section_slug/contents'      => 'section_contents#index',  as: 'section_contents'
      post 'sections/:section_slug/contents'      => 'section_contents#create'
      get  'sections/:section_slug/contents/new'  => 'section_contents#new',    as: 'new_section_content'
      get  'sections/:section_slug/contents/:id'  => 'section_contents#show',   as: 'section_content'
      resources :contents, only: [:index, :show]
    end
  end

  namespace :admin, path: '/pastouch', constraints: https_constraint do
    mount Resque::Server, at: '/jobs', as: 'jobs'
    get '/' => 'monitoring#index', as: :root
    resources :users, only: [:index, :show] do
      member do
        get :become
      end
    end
    get '/metrics' => 'metrics#index'
  end

  # Public website
  root 'home#index'
  get '/about'   => 'home#about'
  get '/privacy' => 'home#privacy'
  get '/terms'   => 'home#terms'
  get '/styleguide' => 'home#styleguide'
  resources :leads,       only: [:new, :create]

  # oauth callbacks
  match 'auth/:provider/callback', to: 'social_channels#new', via: [:get, :post]
  get   'auth/failure',            to: 'social_channels#fail'

  #main app, https only
  scope '/app', constraints: https_constraint do

    resource :api_explorer, only: [:show] do
      post :select
      post :run
    end

    resources :invitations, only: [:create]

    devise_for :users, class_name: 'CB::Core::User', controllers: { registrations: "registrations" }

    #user_setup : tunnel after sign up
    get    'users/setup'                          => 'user_setup#new',  as: :new_user_setup
    delete 'users/setup/website_channel'          => 'user_setup#cancel_website_channel', as: :cancel_website_channel
    delete 'users/setup/social_channel/:provider' => 'user_setup#cancel_social_channel',  as: :cancel_social_channel

    resources :content_types
    resources :publications, only: [:index, :create, :destroy] do
      member do
        get :show_expiration
        put :update_expiration
      end
    end

    resources :contents do
      post :markdown_preview, on: :collection
    end

    resources :channels, :social_channels, :api_channels, :messaging_channels do
      member do
        get  :check_credentials
        get  :reset_access_token
        post :open
        post :close
      end
    end

    resources :contacts, only: [:create]

    get  "channel_unsubscriptions/:channel_id/new" => "channel_unsubscriptions#new",    as: :new_channel_unsubscription
    post "channel_unsubscriptions/:channel_id"     => "channel_unsubscriptions#create", as: :channel_unsubscription

    # ajax direct_to_cloud upload
    post "upload/sign_form"
    get "upload/upload_done"
    get "upload/new", as: 'new_upload'
    resource :multi_upload, only: [:new, :create]

    #mock storage and image resizing in the cloud
    unless Rails.env.production?
      post "storage_mock/image"                                 => "storage_mock#upload_image"
      get  "storage_mock/image/:key"                            => "storage_mock#download_image", constraints: {key: /.*/}
      get  "storage_mock/channel/channels/css/:channel_id/:key" => "storage_mock#download_css"

      get "resizer_mock/resize_image"                           => "resizer_mock#resize_image", as: :resize_image
    end

    get '/' => 'dashboard#index', as: :dashboard

    resource :announcement, only: [:show] do
      get :close
    end

    get '/help/markdown' => 'help#markdown', as: :markdown_help
  end

  # catch all /app and /pastouch without https and redirect to same url using https
  match "app(/*path)",      constraints: http_catchall, via: [:get], to: redirect { |params, request| "https://" + request.host_with_port + request.fullpath }
  match "pastouch(/*path)", constraints: http_catchall, via: [:get], to: redirect { |params, request| "https://" + request.host_with_port + request.fullpath }
end

app/models/cb/core/content.rb
class CB::Core::Content < ActiveRecord::Base
  extend FriendlyId

  before_save :refresh_exportable_properties_if_properties_changed
  after_save  :propagate_slug_change_to_website_publications

  belongs_to :content_type, counter_cache: true
  belongs_to :owner, class_name: 'CB::Core::User'

  has_many :publications, dependent: :destroy
  has_many :published_channels, through: :publications, source: :channel

  serialize :properties, Hash
  serialize :exportable_properties, Hash

  validates_presence_of :title, :content_type_id

  friendly_id :title, use: [:slugged, :scoped], scope: :owner

  paginates_per 10

  scope :owned_by, -> (user) {where(owner_id: model_id(user))}
  scope :of_type, -> (type) {where(content_type_id: model_id(type))}
  scope :recent, -> { order('updated_at DESC') }
  scope :published_on_channel, -> (channel) {joins(:publications).where('publications.channel_id = ?', channel.id)}
  scope :search_on_title, -> (search_string) { where('title @@ ?', search_string) }

  def publications_by_channel
    h = {}
    publications.each {|pub| h[pub.channel_id.to_s] = pub}
    h
  end

  def active_social_publications
    publications.to_a.select{ |publication| publication.provider_ref.present? }
  end

  def refresh_exportable_properties_if_properties_changed
    set_exportable_properties if properties_changed?
  end

  def set_exportable_properties pre_loaded_properties=nil
    type_properties = pre_loaded_properties || content_type.properties.includes(:content_type)
    result = {}
    first_media_prop, first_url_prop = nil, nil

    type_properties.each do |property|
      first_media_prop   = property if first_media_prop.nil? && filled_media_property?(property)
      first_url_prop     = property if first_media_prop.nil? && first_url_prop.nil? && filled_url_property?(property)
      result[property.name] = { 'title' => property.title,
                                'value' => (property.export_value(self.properties[property.id.to_s]) if self.properties.present?),
                                'type'  => property.content_type.name,
                                'i18n'  => self.content_type.by_platform }
    end

    set_first_image_fields(first_media_prop, first_url_prop, result)

    self.exportable_properties = result
  end

  def exportable_properties
    pties = self.read_attribute(:exportable_properties)
    pties.each do |name, property|
      property['title'] = I18n.t("content_type_properties_name.#{self.content_type.name}.#{name}") if property['i18n']
    end
    pties
  end

  def first_image_property
    exportable_properties[first_image_property_key] if first_image_property_key
  end

  def first_textual_property_key
    return @first_textual_property_key if @first_textual_property_key
    @first_textual_property_key = first_property_key_by_types(['text', 'memo', 'phone', 'email'])
  end

  def first_textual_property
    exportable_properties[first_textual_property_key] if first_textual_property_key
  end

  def should_generate_new_friendly_id?
    @slug_changing = title_changed?
  end

  def propagate_slug_change_to_website_publications
    if @slug_changing
      self.publications.joins(:channel).where('channels.type = ?', 'CB::Core::WebsiteChannel').update_all(url_alias: self.slug)
    end
  end

private

  def first_property_key_by_types types
    property_key = nil
    exportable_properties.each do |property_name, property|
      if types.include? property['type']
        property_key = property_name
        break
      end
    end
    property_key
  end

  def filled_media_property? property
    ['image', 'image_gallery'].include?(property.content_type.name) && self.properties.try(:[], property.id.to_s).present?
  end

  def filled_url_property? property
    property.content_type.name == 'url'  && self.properties.try(:[], property.id.to_s).present?
  end

  def set_first_image_fields media_prop, url_prop, props_hash
    if media_prop
      self.first_image_property_key  = media_prop.name
      first_image_value              = props_hash[media_prop.name]
      self.first_image_property_url  = CB::Core::Media.thumbnail_url(first_image_value['value'].is_a?(Array) ? first_image_value['value'].first.try(:[],'url') : first_image_value['value'])
    elsif url_prop
      self.first_image_property_url  = CB::Core::Media.image_for_url(props_hash[url_prop.name]['value'])
      self.first_image_property_key  = self.first_image_property_url.present? ? url_prop.name : nil
    else
      self.first_image_property_key = nil
      self.first_image_property_url = nil
    end
  end

end

app/models/cb/core/content_type.rb
class CB::Core::ContentType < ActiveRecord::Base
  extend FriendlyId
  after_create :add_id_to_slug, :add_usage_for_owner

  has_many   :properties, -> { order :position } , class_name: 'CB::Core::ContentProperty', foreign_key: :father_type_id, dependent: :destroy
  has_many   :contents, class_name: 'CB::Core::Content', dependent: :destroy
  has_many   :sections, class_name: 'CB::Core::Section', dependent: :destroy

  belongs_to :owner, class_name: 'User'
  belongs_to :origin_type, class_name: 'CB::Core::ContentType'

  accepts_nested_attributes_for :properties, allow_destroy: true
  validates_presence_of :title

  friendly_id :title_for_slug, use: [:slugged, :scoped], scope: :owner, slug_column: :name

  def title_for_slug
    by_platform? ? title : "#{title}_#{id}"
  end

  def translated_title
    by_platform? ? I18n.t("content_type_name.#{name}") : title
  end

  def add_id_to_slug
    unless by_platform?
      slug = nil
      self.save!
    end
  end

  def should_generate_new_friendly_id?
    title_changed?
  end

  scope :owned_by,          -> (user) {where(owner_id: user.id)}
  scope :with_owner,        -> {includes(:owner)}
  scope :basic,             -> {where(composite: false)}
  scope :usable_by_default, -> {where(usable_by_default: true)}

  def add_usage_for_owner
    create_usage(owner_id) if owner_id
  end

  def add_usage_for_user user
    create_usage user.id
  end

  def owned_by? user
    owner_id == user.id
  end

  def properties_id_hash
    self.properties.pluck(:name, :id).to_h
  end

  alias_method :can_he_edit?, :owned_by?

private

  def create_usage user_id
    CB::Core::ContentTypeUsage.create!(user_id: user_id, content_type_id: self.id)
  end

end

app/controllers/api/v1/contents_controller.rb
class API::V1::ContentsController < API::V1::ChannelSecuredController

  def index
    api_response rescuer(CB::Query::Publication.new(@channel)).list
  end

  def show
    api_response rescuer(CB::Query::Publication.new(@channel)).find_by_url_alias(params[:id])
  end
end

app/controllers/contents_controller.rb
class ContentsController < ApplicationController
  include ContentHelper
  before_action {section 'content'}
  before_action :authenticate_user!, :load_services

  def index
    @display_mode = set_display_mode
    per_page = @display_mode == 'grid' ? 15 : 6
    if params[:content_type_id].present? && params[:content_type_id] != 'all'
      @type     = @type_service.find(params[:content_type_id])
      contents_query = @content_service.recent_for_type(@type)
    else
      contents_query = @content_service.recent
    end

    contents_query = contents_query.search_on_title(params[:search]) if params[:search].present?

    @contents = contents_query.page(params[:page]).per(per_page)
    @types    = @type_service.user_types
  end

  def show
    @content = @content_service.find(params[:id])
    @type    = @content.content_type
  end

  def new
    @type                     = @type_service.find(params[:content_type_id])
    @newly_created, @content  = @content_service.create(@type, title: t('.new_title', title: @type.translated_title.downcase))
    if @newly_created
      @content.title = nil
    else
      flash[:alert] = t('.error')
      redirect_to contents_path
    end
  end

  def create
    @type            = @type_service.find(params[:content][:content_type_id])
    result, @content = @content_service.create(@type, content_params(@type))
    if result
      redirect_to content_path(@content.id), notice: t('.notice', title: @type.translated_title)
    else
      render :new
    end
  end

  def edit
    @content  = @content_service.find(params[:id])
    @type     = @content.content_type
  end

  def update
    @type            = @type_service.find(params[:content][:content_type_id])
    result, @content = @content_service.update(params[:id], content_params(@type))
    if result
      redirect_to content_path(@content.id), notice: t('.notice', title: @type.translated_title)
    else
      render :edit
    end
  end

  def destroy
    destroyed, content = @content_service.destroy(params[:id])
    type = content.content_type
    if destroyed
      flash[:notice] = t('.notice', type: type.translated_title, content: content.title) unless params[:no_flash].present?
    else
      flash[:alert] = t('.error', type: type.translated_title, content: content.title)
    end
    redirect_to contents_path
  end

  def markdown_preview
    render text: markdown(params[:text])
  end

private

  def load_services
    @type_service    = CB::Manage::ContentType.new(current_user)
    @content_service = CB::Manage::Content.new(current_user)
    @channel_service = CB::Manage::Channel.new(current_user)
  end

  def content_params type
    #params.require(:content).permit(:title, properties: type.properties.map{|p| "#{p.id}"})
    params.require(:content).permit(:title).tap do |whitelisted|
      whitelisted[:properties] = params[:content][:properties]
    end
  end

  def set_display_mode
    return session['content_layout'] = params[:display_mode] if ['cards', 'grid'].include?(params[:display_mode])
    return session['content_layout'] = 'cards' unless session['content_layout'].present?
    session['content_layout']
  end
end

app/views/contents/_content_filter.html.erb
<% types_select = {t('.all_formats') => 'all'} %>
<% types.each {|type| types_select[type.translated_title] = type.id if can_display_type?(type)} %>
<% selected_value = current_type ? current_type.id : 'all' %>
<%= form_tag(contents_path, method: :get ) do %>
	<div class="row">
			<div class="cell ratio1">
					<%= select_tag  "content_type_id",
									options_for_select(types_select, selected_value),
									onchange: "this.form.submit()",
									class: 'fancy' %>
			</div>
			<div class="cell ratio1">
				<%= search_field_tag :search, params[:search], autosave: true, placeholder: t('.search'), autofocus: 'autofocus' %>
			</div>
	</div>
<% end %>

app/views/contents/_contents_cards.html.erb
<% @contents.each do |content| %>
    <% type = @type || content.content_type %>
    <article class="box content" id="content_<%=content.id%>">
        <header class="box-hd">
            <%= link_to type.translated_title, contents_path(content_type_id: type.id) %>
            <%= link_to '', content_path(content.id), method: :delete, data: {icon: raw("&#xe00b;"), confirm: t('contents.shared.confirm')}, class: "remove rFloat" %>
            <%= link_to '', edit_content_path(content.id), id: "content_edit_#{content.id}", class: 'rFloat', data: {icon: raw("&#xe00c;"), no_turbolink: true}%>
        </header>
        <%= link_to content_path(content.id), class: 'linkZone' do %>
            <div class="box-bd">
                <% if content.first_image_property_url.present? %>
                    <%= display_image(content.first_image_property_key, content.first_image_property_url, nil, wrapper_class: "box--md") %>
                <% end %>
                <h2><%= content.title %></h2>
                <div class="box--ct">
                    <p>
                        <time datetime="<%=l(content.updated_at, format: :html5)%>">
                            <%= time_ago_in_words content.updated_at %>
                        </time>
                    </p>
                    <% if content.first_textual_property_key.present? %>
                        <%= display_content_property(content.first_textual_property_key, content.first_textual_property, display_label: false) %>
                    <% end %>
                </div>
            </div>
        <% end %>
        <footer class="box-ft">
            <%= link_to publications_path(content_id: content.id), remote: true, id: "show_pub_#{content.id}", data: {icon: raw("&#xe010;")} do %>
                <span id="pub_count_<%=content.id%>"><%= content.publications_count %></span> <%=t('.publications')%>
            <% end %>
            <%= link_to t('contents.shared.hide_publications'), '#', id: "hide_pub_#{content.id}", class: 'hide_pub', style: 'display: none', data: {content_id: content.id.to_s, icon: raw("&#xe015;")} %>
            <div id="publications_for_<%=content.id%>" style="display: none"></div>
        </footer>
    </article>
<% end %>

app/views/contents/_contents_grid.html.erb
<div class="box">
	<div class="box-bd grid">
		<% @contents.each do |content| %>
		    <% type = @type || content.content_type %>
			<div class="row with-sub-row with-butn-mob _withButnMob" id="content_<%=content.id%>">
			    <%= link_to '', '#', data: {icon: raw("&#xe000;")}, class: "butn-mob-menu _butnMobMenu" %>
				<div class="cell ratio3">
					<%= link_to content.title, content_path(content.id) %>&nbsp;&nbsp;
			    </div>
			    <div class="cell ratio1 nomob">
			    	<%= link_to type.translated_title, contents_path(content_type_id: type.id) %>
			    </div>
			    <div class="cell ratio2">
			    	<div class="cTxt">
				    	<%= link_to publications_path(content_id: content.id), remote: true, id: "show_pub_#{content.id}", data: {icon: raw("&#xe010;")} do %>
			                <span id="pub_count_<%=content.id%>"><%= content.publications_count %></span> <%=t('.publications')%>
			            <% end %>
			            <%= link_to t('contents.shared.hide_publications'), '#', id: "hide_pub_#{content.id}", class: 'hide_pub', style: 'display: none', data: {content_id: content.id.to_s, icon: raw("&#xe015;")} %>
		            </div>
			   	</div>
			    <div class="cell">
			    	<div class="butn-mob _butnMob">
				    	<%= link_to '', edit_content_path(content.id), id: "content_edit_#{content.id}", data: {icon: raw("&#xe00c;"), no_turbolink: true}, class: 'butn-no-text' %>
				    	<%= link_to '', content_path(content.id), method: :delete, data: {icon: raw("&#xe00b;"), confirm: t('contents.shared.confirm')}, class: "remove butn-no-text" %>
			    	</div>
			    </div>
		 	</div>
		 	<div class="sub-row">
		 		<div id="publications_for_<%=content.id%>" style="display: none"></div>
		 	</div>
		<% end %>
	</div>
</div>

app/views/contents/_create_content_button.html.erb
<%= link_to t('actions.create'), '#', class: 'butn action triggerMenu', data: {icon: raw("&#xe001;"), menu_id: 'createContent'} %>
<div id="createContent" class="butnMenu" style='<%= params[:unfold_create_btn] == 'true' ? 'display:block;' : 'display:none;' %>' data-no-turbolink>
    <h2><%= t '.create' %></h2>
    <% if current_type %>
        <%= link_to current_type.translated_title, new_content_path(content_type_id: current_type.id), data: (current_type.picto.present? ? {icon: raw(current_type.picto)} : nil), class: "butn action#{current_type.by_platform? ? ' shared' : ''}" %>
        <% if types.size > 1 %>
            <h2><%= t '.create_other' %></h2>
        <% end %>
    <% end %>
    <ul>
        <% types.each do |type| %>
            <% if can_display_type?(type) %>
                <% unless current_type && current_type.id == type.id %>
                    <li>
                        <%= link_to type.translated_title,
                                    new_content_path(content_type_id: type.id),
                                    data: (type.picto.present? ? {icon: raw(type.picto)} : nil),
                                    class: "butn action#{type.by_platform? ? ' shared' : ''}" %>
                    </li>
                <% end %>
            <% end %>
        <% end %>
    </ul>
    <%= t('.tip') %> "<%= t('content_type_name.link') %>"
</div>

app/views/contents/_form.html.erb
<% content_for :load_script do %>
    cb.decorateImageWidgets();
    cb.decorateImageGalWidgets();
    cb.decorateMarkdownWidgets('<%=asset_path('plugins/epiceditor/epiceditor_preview.css')%>');
<% end %>

<%= form_for @content, as: :content, url: content_path(@content.id) do |f| %>

    <%= render "shared/error_messages", target: @content %>

    <%= f.hidden_field :content_type_id %>
    <div>
        <% title_label = @content.content_type.title_label %>
        <%= f.text_field :title, autofocus: true, required: true, placeholder: (title_label.present? ? title_label : t('.add_title')) , class: 'formTitle', id: 'content_title'  %>
        <% unless @newly_created %>
            <%= f.label :slug %>
        	<%= f.text_field :slug, disabled: true %>
        <% end %>
    </div>
    <%= f.fields_for :properties, OpenStruct.new(@content.properties) do |builder| %>
        <% @content.content_type.properties.each do |field| %>
            <%= render "contents/fields/#{field.content_type.name}", field: field, f: builder, content_id: @content.id, content_type: @content.content_type %>
        <% end %>
    <% end %>

    <% if @newly_created %>
        <%= f.submit t('.submit_create') %>
        <%= link_to t('actions.cancel'), content_path(@content.id, no_flash: true), method: :delete, class: 'butn' %>
    <% else %>
        <%= f.submit %>
        <%= link_to t('actions.cancel'), contents_path(@type.id), class: 'butn' %>
        <%= link_to t('actions.delete'), content_path(@content.id), method: :delete, class: 'butn delete', data: {confirm: t('contents.shared.confirm') } %>
    <% end %>

<% end %>

app/views/contents/_upload_form.html.erb
<% messages[:typeError] 		#||= t('view.upload.type_error') 		%>
<% messages[:uploadError] 		#||= t('view.upload.upload_error') 		%>
<% messages[:postUploadError] 	#||= t('view.upload.post_upload_error') %>
<% messages[:limits] 			#||= t('view.upload.limits') 			%>
<% messages[:inProgress] 		#||= t('view.upload.in_progress')		%>
<% messages[:success] 			#||= t('view.upload.success')			%>
<% messages[:doneLinkLabel] 	#||= t('view.upload.done_link_label')	%>
<% messages[:select] 	        	                                    %>

<div>
	<form id="<%=form_id%>" action="<%=storage.url%>" method="post" enctype="multipart/form-data">
		<div class="errorMsg error" style="display:none"></div>
		<div class="successMsg notice" style="display:none"></div>
	    <input type="hidden" name="acl" value="public-read">
	    <input type="hidden" name="bucket" value="<%=storage.bucket%>">
	    <input type="hidden" name="Content-Type" value="image/jpeg">
	    <input type="hidden" name="key" >
	    <input type="hidden" name="<%= storage.provider == 'AWS' ? 'AWSAccessKeyId' : 'GoogleAccessId'%>" value="<%=storage.access_key%>">
	    <input type="hidden" name="policy" value="policy">
	    <input type="hidden" name="signature" value="signature">
	    <% if transport == 'iframe' %>
	    	<input type="hidden" name="success_action_redirect" value="redirect">
	    <% end %>
	    <div class="photosUpload">
    	    <div class="fileUpload">
		        <div class="butn action fileinput-button">
					<span><%= messages[:select] %></span>
					<input class="fileinput" name="file" type="file">
				</div>
		    </div>

		    <progress value="0" max="100" style="display: none;">
		    	<% if transport == 'iframe' %>
	    			<span><%= messages[:inProgress] %></span>
	    		<% else %>
	    			<span></span>
	    		<% end %>
		    </progress>

	        <div class="filesSize mtm tac">
	        	<%= messages[:limits] %>
	        </div>
		    <div class="loading" style="display:none">
		        <%= messages[:inProgress] %>
		    </div>
		</div>
	</form>
</div>

<script>
    uploadifyForm('#<%=form_id%>', '<%=media[:name]%>', '<%=upload_sign_form_path %>', '<%=transport%>', '<%= doneLinkUrl%>', '<%= storage.storage_name%>', '<%=raw(escape_javascript(messages.to_json))%>');
</script>

app/views/contents/edit.html.erb
<section class="contents">
	<h1 class="h2"><%= t '.title' %></h1>
	<div class="box">
		<div class="box-bd">
		    <%= render 'form' %>
		</div>
	</div>
</section>

app/views/contents/index.html.erb
<% content_for :load_script do %>
    cb.togglePublications();
    cb.triggerPublications();
    cb.decorateMenuButtons();
    cb.decorateMobileButtons();
<% end %>

<section class="contents">
    <h1 class="h2"><%= t '.title' %></h1>
    <section class="actions">
        <%= render partial: 'create_content_button', locals: {types: @types, current_type: @type} %>
        <%= render partial: 'content_filter',        locals: {types: @types, current_type: @type} %>
        <%= link_to '', params.merge!(display_mode: 'grid', page: 1), data: {icon: raw("&#xe604;")}, class: "switch-view #{@display_mode=='grid' ? ' active' : ''}" %>
        <%= link_to '', params.merge!(display_mode: 'cards', page: 1), data: {icon: raw("&#xe603;")}, class: "switch-view #{@display_mode=='cards' ? ' active' : ''}" %>
    </section>
    <div id="content_list">
        <%= render "contents_#{@display_mode}" %>
        <%= paginate @contents %>
    </div>
</section>

app/views/contents/new.html.erb
<section class="contents">
	<h1 class="h2"><%= t '.title' %></h1>
	<div class="box">
		<div class="box-bd">
		   	<%= render 'form' %>
		</div>
	</div>
</section>

app/views/contents/show.html.erb
<% content_for :load_script do %>
    cb.displayPublicationZone('<%= publications_path(content_id: @content.id) %>', $('#publications_for_<%=@content.id%>'));
    cb.triggerPublications();
    cb.colorizeCode();
    cb.decorateGalleries();
    cb.decorateUrls();
    cb.decorateMarkdownLinks();
<% end %>

<section class="contents">
    <h1 class="h2"><%= t '.title' %></h1>
    <section class="box publications">
        <h3>
            <%= raw t('.published_on', id: @content.id, count: @content.publications_count) %>
        </h3>
        <div id="publications_for_<%=@content.id%>"></div>
    </section>

    <article class="box content">
        <header class="box-hd">
            <%= link_to @type.title, contents_path(content_type_id: @type.id) %>
            <%= link_to '', content_path(@content.id), method: :delete, data: {icon: raw("&#xe00b;"), confirm: t('contents.shared.confirm')}, class: "remove rFloat" %>
            <%= link_to '', edit_content_path(@content.id), class: 'rFloat', data: {icon: raw("&#xe00c;"), no_turbolink: true} %>
        </header>
        <div class="box-bd">
            <h1 id="content_title"><%= @content.title %></h1>
            <% @content.exportable_properties.each do |prop_name, property| %>
                <%= display_content_property prop_name, property %>
            <% end %>
        </div>
        <footer class="box-ft">
        </footer>
    </article>
</section>

<%= render 'cb-render/js_templates' %>